--USERS:
--Fill "users" table with fake users (all users' passwords will be 'one'):

INSERT INTO "users"
("username", "firstName", "lastName", "profilePic", "password", "address", "city", "state", "zip", "type", "website", "bio")


VALUES 
('Mac@gmail.com', 'McKynlee', 'Westman', 'https://karaspartyideas.com/wp-content/uploads/2016/11/Bike-Themed-Birthday-Party-via-Karas-Party-Ideas-KarasPartyIdeas.com28.jpeg', '$2a$10$d.tw3AyrHON3AynvQDuoN.my8uxemJ7KZhzc7fcRMAHiuMpxIwh/u', '4946 Walnut St', 'Kansas City', 'MO', 64112, 'planner', 'https://mckynlee.github.io/', 'Avid organizer of bike rallies - the non-motorized kind!'),
('SirBill@gmail.com', 'William', 'Krug', 'https://partycity6.scene7.com/is/image/PartyCity/_pdp_sq_?$_1000x1000_$&$product=PartyCity/819485', '$2a$10$mnm8InlV1d1tnUTAGywETO1w6u/p/2kD.iUN9kJ25Ww6cBxNaHjzi', '11 Knights Way', 'Minneapolis', 'MN', 55111, 'vendor', 'https://www.imdb.com/title/tt0183790/', 'Ready to help you plan your next Rennaissance affair down to the hilt of your sword!'),
('LilRusty@gmail.com', 'Dusty', 'Meyers', 'http://basementrejects.com/wp-content/uploads/2014/08/dungeons-dragons-2000-thora-birch-riding-dragon-savina-300x166.jpg', '$2a$10$nxWzD4fOt4n72TbnMlYXQO/yZknXnREW7s9DJY9IP0dIJG2PzsbiW', '77 DnD Blvd', 'Lawrence', 'KS', 66044, 'planner', 'https://www.imdb.com/title/tt0190374/', 'Looking to plan the wedding of my lifetime!'),
('JDog@gmail.com', 'John', 'Shands', 'https://www.rawmusictv.com/images/og-share-image/best-swedish-rock-bands.jpg', '$2a$10$vSH/PXClWlf3vPlHKRLNXu5TRQPamdzbn921Q7tgtiDsK20SVTB2m', '69 Woodstock Lane', 'Liberty', 'MO', 64068, 'vendor', 'https://www.libertymissouri.gov/1500/Liberty-Summer-Band', 'Able to provide a musical experience that your guests will never forget.'),
('RedRevolt@gmail.com', 'Jason', 'Lin', 'https://www.alpineartscenter.org/images/stories/setup_pictures/birthday%20copy.jpg', '$2a$10$coxFv5Ll23qca8Dp4LZ9T.UNlQTDQ32BM1FHXrKVqNwEJVmwWs8hG', '123 Four Ave', 'St. Cloud', 'MN', 56301, 'planner', 'https://memes.com/', 'Helping local artists plan gallery-openings throughout the Twin Cities.'),
('MushroomMan@gmail.com', 'Edan', 'Schwartz', 'https://images.ctfassets.net/cnu0m8re1exe/4jaJ338Mbgu42tfIVnvWbp/e2c7e11773ff21b6d6f073fe8b87ece7/shutterstock_734992102.jpg?w=650&h=433&fit=fill', '$2a$10$y1VJWv.1EEpl5cbpp8csguhA8OuXfou32w/wWTA.yrOzrmv6i2zMW', '1 Magic Mushy Rd', 'Minneapolis', 'MN', 55404, 'vendor', 'https://www.birdsandblooms.com/stuff-we-love/gardening-stuff/mushroom-growing-kits/', 'Mushroom-catering specialty; guaranteed to serve only the non-toxic kind.'),
('info@Mintahoe.com', 'Jackie', 'Chan', 'https://www.mintahoe.com/wp-content/uploads/2017/04/MCE_Logo_White-e1492627487357.png', 'one', '2850 Anthony Lane South', 'Minneapolis', 'MN', 55418, 'vendor', 'https://www.mintahoe.com/', 'When you choose Mintahoe Catering &  Events, you choose pease of mind.  Our event experts will help you design the perfect menu with your vision and budget. Envision the Wow.'),
('info@Chowgirls.com', 'Annie', 'Oakley', 'https://www.chowgirls.net/_interface/structure/chowgirls_large.png', 'one', '336 Hoover St NE', 'Minneapolis', 'MN', 55413, 'vendor', 'https://www.chowgirls.net/', 'Whether you are celebrating a grad, a dad, or just have plans for simple al fresco dining this spring and summer, we have got delicious ways to celebrate safely.'),
('info@nafnaf.com', 'Amir', 'Abdul', 'https://2utgaa2m4mzswgysf34qlzz1-wpengine.netdna-ssl.com/wp-content/uploads/logo.svg', 'one', '3340 Central Park Village Drive, Suite 100', 'Egan', 'MN', 55121, 'vendor', 'https://www.nafnafgrill.com/', 'We promise to be your guide to exploring the best flavors of the Middle East each time we make our handmade dishes, like pillowy pita, crispy falafel, savory shawarma, and our scratch-made signature sauces.'),
('dine@CRAVE.com', 'Domingo', 'Chavez', 'http://cravecatering.com/wp-content/uploads/2017/02/CRAVE_CateringEvents_Logo_1_26_17_Black_RedV.png', 'one', '2100 Summer St NE', 'Minneapolis', 'MN', 55413, 'vendor', 'http://cravecatering.com/', 'Inspired by our passion for quality food and our love of helping guests create one of a kind memories, CRAVE Catering is a full service Minneapolis catering company dedicated to making your event unforgettable!'),
('info@deco.com', 'Hans', 'Gruber', 'https://www.decocatering.com/wp-content/uploads/2015/11/deco_catering_logo.png', 'one', '2010 E Hennepin Ave Ste 7', 'Minneapolis', 'MN', 55413, 'vendor', 'http://www.decocatering.com', 'Located in Minneapolis, The Deco Catering is a premier Minnesota caterer, founded by Soile Anderson in 1982. The Deco Catering offers award winning authentic European catering rich with flavor, artistic flair, and design.'),
('info@commonroots.com', 'Bonnie', 'Patterson', 'https://static1.squarespace.com/static/51018139e4b0d171103d3396/t/598b4efddb29d6084ce80dab/1609430941993/?format=1500w', 'one', '2558 Lyndale Ave S', 'Minneapolis', 'MN', 55405, 'vendor', 'https://www.commonrootscatering.com/', 'We are a full-service Minneapolis / St. Paul caterer providing our clients with good food made from scratch and exceptional service.  We will make your event memorable with our modern take on classic American cuisine using local and organic ingredients.'),
('events@walkerart.com', 'Luke', 'Wagner', '', 'one', '725 Vineland Pl', 'Minneapolis', 'MN', 55403, 'vendor', 'https://walkerart.org/events-catering/', 'The Walker Art Center, one of the most celebrated art museums in the country, is known for its innovative presentations and acclaimed collections across the spectrum of the visual, performing, and media arts, housed within an award-winning civic landmark. Amid beautiful galleries, the Walker also offers unique spaces for indoor and outdoor private rentals for artful celebrations, refined receptions, unforgettable weddings, and state-of-the-art corporate events. The iconic building features flexible spaces with high-tech amenities for nearly any size gathering—including a theater, street-level and roof-top terraces, plazas, gardens, and lounges.'),
('info@five.com', 'Amber', 'Ebert', 'https://www.fiveeventcenter.com/wp-content/uploads/2015/12/five_logo_gradient-copy.png', 'one', '2917 Bryant Avenue South', 'Minneapolis', 'MN', 55408, 'vendor', 'https://www.fiveeventcenter.com/', 'The historic building boasts a full upstairs remodel while retaining nods to the original elements: wood floors and exposed brick call to times past, while New York contemporary lighting and artwork inject the space with unique personality. The renovated space showcases up to the minute technology – including an HD projector and large 110-inch retractable screen, customizable Gobo lighted image projector (perfect for your new wedding monogram), complete sound system compatible with all Apple devices, and high-speed wireless internet, which will make social media posting a breeze for your guests!'),
('karen@aria.com', 'Karen', 'Ashley', 'http://static1.squarespace.com/static/593dc4ac5016e1368cc779ab/t/5f356f623d689a54ab9534fa/1615984167809/?format=1500w', 'one', '105 North 1st Street', 'Minneapolis', 'MN', 55401, 'vendor', 'http://www.ariampls.com/', 'As a former theater our open and flexible floor plan, soaring 30-foot ceilings, amazing acoustics, and plentiful rigging points for décor and lighting, ensure that logistics are never in the way of bringing your event dreams to life.'),
('events@lxmpls.com', 'Jeremy', 'Ryan', 'https://lxmpls.com/wp-content/uploads/2019/05/LXMPLS-side-white-44.png', 'one', '10 South 5th St Suite 111', 'Minneapolis', 'MN', 55402, 'vendor', 'https://lxmpls.com/', 'We are Downtown Minneapolis’ most versatile venue, located at the intersection of Hennepin Avenue and South 5th Street in the dazzling Lumber Exchange Building.'),
('infor@abluea.com', 'Blake', 'Reacher', 'https://www.abulae.com/mt-content/uploads/2016/05/ab-horizontal-web-white.png', 'one', '255 6th Street E Sixth Floor', 'Saint Paul', 'MN', 55101, 'vendor', 'https://www.abulae.com/', 'Instead of designing the event around the building, we designed the building around the event.'),
('info@Midpointe.com', 'Shayla', 'Johnson', 'https://static1.squarespace.com/static/5761bf14b3db2bca65bc21d0/t/5ab9540a2b6a28f2b9fbec70/1599146836852/?format=1500w', 'one', '415 Pascal Street North', 'St. Paul', 'MN', 55104, 'vendor', 'https://midpointeeventcenter.com/', 'Our mission is to provide an elegant facility, excellent staff, and superior service to our wonderful and diverse community. We believe that every guest is important and we help them create memories to last a lifetime'),
('AmyZaroff@gmail.com', 'Amy', 'Zaroff', 'https://static1.squarespace.com/static/5e593fb04aabfd3b920e8a9b/t/5e594ab74f9ff3249dd1c0fe/1604376932856/?format=1500w', 'one', '11267 Overlook Drive', 'Minnetonka', 'MN', 55305, 'vendor', 'https://www.amyzaroff.com/', 'We are a boutique, multi-channel, creative agency that has produced over 1,500 events across the United States and Canada. We are smart, fun loving and creative people brought together by a shared passion for attention to detail and bringing joy to those who attend our activations and events.'),
('info@yandievents.com', 'Ichabod', 'Yentis', 'https://static1.squarespace.com/static/57fc161ef5e2311c16ea5b20/t/59332e2a6b8f5beeb5aa1070/1593549108335/?format=1500w', 'one', '920 E Lake St # 136 N', 'Minneapolis', 'MN', 55407, 'vendor', 'https://www.yievents.com/', 'We are committed to helping you create your special event just the way you imagined it and more! We listen to your needs, desires, and create custom designs with our in-house event decoration rentals and design services. We work with you to make the day you have dreamed of even more special.'),
('janet@blaisdell.com', 'Janet', 'Mosley', 'https://static1.squarespace.com/static/59a44761ebbd1a1312cf985b/t/59ee37c34611a04b1e3b5249/1615823840923/?format=1500w', 'one', '2322 Blaisdell Avenue', 'Minneapolis', 'MN', 55404, 'vendor', 'https://www.theblaisdell.com/', 'A newly renovated event venue in the heart of Minneapolis combining elegant style with a modern sensibility, offering a unique space for weddings, corporate events & more.'),
('Blush@gmail.com', 'Colleen', 'Nava', 'https://static1.squarespace.com/static/5dc43efb2e2b2933cf3e1d98/t/5e41b5da7bc3911e7c2bfbce/1606628440231/?format=1500w', 'one', '', 'Inver Grove Heights', 'MN', 55076, 'vendor', 'https://www.blusheventsmn.com/', 'Simply put, I absolutely love all things design! Each project is an exciting challenge for me as I translate ideas and visions into real life. The special events we celebrate are often important milestones in our lives and deserve to be remembered in a beautiful way… and unique, artful statement decor will do just that for you and your guests! A stunning photo backdrop, welcome wall, or perhaps a lovely balloon piece will set the tone for these momentous occasions. '),
('AmazingScott@live.com', 'Scott', '', 'http://static1.squarespace.com/static/58b8608537c58149fafa08e0/t/5e9e0a8768b9b14d0a18752f/1579735304886/?format=1500w', 'one', '', 'Minneapolis', 'MN', 55409, 'vendor', 'http://www.amazingscott.com/', 'The Amazing Scott features international award-winning balloon Artist and Certified Balloon Artist (CBA), Scott Nichols CBA. With Beautiful balloon sculptures, Outstanding balloon decor, and Amazing balloon Entertainment, we offer unique upgrades to any party or event to make it "Magical" for an unforgettable experience.'),
('leslie@decorforweddings.com', 'Leslie', 'Goodman', '', 'one', '100 West Franklin Avenue Suite 202', 'Minneapolis', 'MN', 55404, 'vendor', 'http://www.decorforweddings.com/', 'Distinctive decor, floral & styling for weddings & events in Minneapolis, St. Paul & the Twin Cities Metro Area of Minnesota.'),
('aandjparty@aol.com', 'James', 'Anderson', '', 'one', '', 'Bloomington', 'MN', 55431, 'vendor', 'http://www.ajpartyrental.com/', 'We bring all of your rental needs to you! No matter your location whether it be Minneapolis, Edina, Lakeville, Bloomington, Farmington Apple Valley or any surrounding Twin Cities area, we charge a reasonable fee to ensure you have what you need for your event. Tables, Chairs, Canopies, and much more- We have what you need to make your party the best it can be!'),
('partyrentals@broadwayparty.com', 'Jonas', 'Smith', '', 'one', '8101 Ashton Ave NE', 'Fridley', 'MN', 55432, 'vendor', 'https://broadwaypartyrental.com/', 'Broadway is a Local Family Owned business & since 1956 we’ve dedicated ourselves to providing quality rental equipment to our community! We’re 2nd Generation owned & operated! Learn more about buying local.'),
('info@minnesota-ice.com', 'Willard', 'Smith', 'https://www.minnesota-ice.com/images/mni-logo2.svg', 'one', '755 Prior Ave. Suite 237', 'St. Paul', 'MN', 55104, 'vendor', 'https://www.minnesota-ice.com/', 'MINNESOTA ICE IS THE LEADING PRODUCER OF PACKAGED ICE, PURE & CLEAR COCKTAIL ICE, KOLD DRAFT ICE CUBES, CRUSHED ICE, SHAVED ICE BLOCKS, SCULPTURE ICE BLOCKS, AND ICE SCULPTURES'),
('tammy@occasionslinen.com', 'Tammy', 'Danger', 'https://www.occasionslinen.com/wp-content/uploads/2016/01/new-logo-wide-xsm.png', 'one', '551 Dorland Rd', 'Maplewood', 'MN', 55119, 'vendor', 'https://www.occasionslinen.com/', 'Whether it’s an intimate gathering or larger gala your event will be remembered for a lifetime. Specialty linens are key to a spectacular table setting and to creating your desired atmosphere. Just remember that your event will be photographed over and over…so you really want to make a lasting impression! Occasions Linen Rental services the Twin Cities and surrounding communities. If there is something that you don’t see on the website let us know we can order it! Together we can create your occasion to remember.'),
('events@festivitiesmn.com', 'Julio', 'Varga', 'https://www.festivitiesmn.com/wp-content/uploads/2016/01/festvities_logo_318x72.jpg', 'one', '10701 Red Circle Drive', 'Minnetonka', 'MN', 55343, 'vendor', 'https://www.festivitiesmn.com/', 'Festivities has the functional, fun & fashionable stuff your event needs, with the design, service & expertise you want.'),
('info@apresparty.com', 'Lindsey', 'Logan', 'https://res.cloudinary.com/expertise-com/image/upload/f_auto,fl_lossy,q_auto:low/remote_media/logos/1573065346_apresparty-com.jpg', 'one', '5801 Clearwater Drive', 'Minnetona', 'MN', 55343, 'vendor', 'http://www.apresparty.com/', 'bI started Après 33 years ago out of the lower level of my home. Purchasing a full line of rental inventory and opening at my first location in time for the hectic Christmas season of 1987. We are now working out of more than 63,000 square feet.io'),
('fun@atouchofmagicentertainment.com', 'Megan', 'Grahm', 'https://atouchofmagicentertainment.com/wp-content/uploads/2018/01/ATOM_Logo.png', 'one', '', 'St. Paul', 'MN', 55113, 'vendor', 'https://atouchofmagicentertainment.com/', 'We are a family owned and operated full-service entertainment company run by professional entertainers.  Founded in 1986, A Touch of Magic, Inc. is located in St. Paul, Minnesota, the Twin Cities, with entertainers/artists who are nationally renowned in addition to being local favorites. What started as a small project to fund a college education,  has grown into a lifelong passion and desire to bring joy & laughter to our clients!  Maybe that’s why we’ve been named “Best Entertainment” in the Twin Cities over and over again.'),
('karaoketwincities@gmail.com', 'Oko', 'Ono', 'http://img1.wsimg.com/isteam/ip/5551b527-c09a-4f5e-ae4c-35a6fe37d268/79f27784-3cce-418a-bc34-7a794d4621e2.jpg/:/rs=h:500,cg:true,m', 'one', '', 'Minneapolis', 'MN', 55406, 'vendor', 'wehttp://karaoketwincities.com/bsite', 'We provide hosted karaoke entertainment to local bars/restaurants as well as the opportunity to rent our equipment with or without a host to suit your entertainment needs.'),
('info@northernsoundentertainment.com', 'Dustin', 'Jaeger', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRur8DoOFGWLDmykCuV6KmqYk84-l3-R1q2pg&usqp=CAU', 'one', '16102 Hawthorn Path', 'Lakeville', 'MN', 55044, 'vendor', 'https://www.northernsoundentertainment.com/', 'The owners of Northern Sound Entertainment have a serious passion for the event service industry. They started this company in 2016 with a vision to shake up the Wedding and Event Services industry.'),
('info@wedphoria.com', 'Michael', 'Wells', 'https://www.minnesotaprodj.com/images/WedPhoria-Banner-hor-300x100.png', 'one', '', 'Clear Lake', 'MN', 55319, 'vendor', 'https://www.minnesotaprodj.com/', 'WedPhoria, formerly known as Minnesota Pro DJ, offers HIGH quality wedding and special event DJ, Photo Booth, Photography, Officiant and Event Planning services.'),
('info@adagiodj.com', 'Roger', 'Moore', 'https://vol7d4dgnq224poreu2v6gqb-wpengine.netdna-ssl.com/wp-content/uploads/sites/22/2017/01/logo-adagio.svg', 'one', '413 Wacouta Street Suite 100', 'Saint Paul', 'MN', 55101, 'vendor', 'https://www.adagiodj.com/', 'When the lights go up and the party’s over, all you’ll have left are the memories. At Adagio Djay Entertainment, we specialize in crafting a symphony of music, melodies and excitement into the perfect experience for the most memorable day of your life. From the first dance to the last—we never forget whose day it is.'),
('info@midwestsound.com', 'Charles', 'Jordan', 'https://static1.squarespace.com/static/54849ccfe4b0b09de1feb208/t/54bdb9c5e4b0a3e130f04409/1608599170100/?format=1500w', 'one', '1900 Oakcrest Ave STE 6', 'Roseville', 'MN', 55113, 'vendor', 'https://www.midwestsound.com/', 'We created the blueprint for wedding DJ entertainment. We continue to set trends and facilitate remarkable receptions. Our unparalleled training and mentorship program makes our DJs exceptional. We perform at 1,900 receptions every year and each is customized to be one of a kind. Our comprehensive online planning process lets our clients have complete control to guarantee a unique and memorable wedding. With our experience and reliability, we will continue to provide amazing wedding DJ entertainment for many years to come.'),
('info@brancatoscatering.com', 'Brandon', 'Castillo', 'http://brancatoscatering.com/wp-content/uploads/b-logo-e1612471991570.png', 'one', '5050 Kansas Ave', 'Kansas City', 'KS', 66106, 'vendor', 'https://brancatoscatering.com/', 'Whether you’re planning an outdoor event or working with one of Kansas City’s hottest venues, our expert coordinators will offer you the latest in food trends and make your event one to remember. We work closely with Kansas City’s top event venues to help provide you with the best service possible for your big day. If you haven’t selected your venue yet we can help guide you in finding the perfect fit for your big day. Our coordinators will work with you from planning to execution, providing you with expert guidance leading up to your event and throughout your big day making sure your expectations are exceeded.'),
('moxiecatering@gmail.com', '', '', 'http://www.moxiecatering.com/moxieFront01.jpg', 'one', '1617 Genessee St', 'Kansas City', 'MO', 64102, 'vendor', 'http://www.moxiecatering.com/', ''),
('chef@thebluepot.com', 'Kelly', 'Bundy', 'https://thebluepot.com/wp-content/uploads/2016/09/BluePotLogoWide.jpg', 'one', '8133 Wornall Road', 'Kansas City', 'MO', 64114, 'vendor', 'https://thebluepot.com/', 'Kansas City’s premier catering and event designer for weddings, corporate and social events, since 2006. Delight your guests with seasonal, made-from-scratch menu items inspired by the best ingredients.'),
('info@grandmas.com', 'Vivan', 'Heart', 'https://grandmascatering.com/wp-content/themes/grandmas/assets/img/logo.png', 'one', '2800 Guinotte Ave', 'Kansas City', 'MO', 64120, 'vendor', 'https://grandmascatering.com/', ''),
('info@twositers.com', 'Michele', 'Fisher', 'http://beta.twosisterscateringkc.com/wp-content/uploads/2013/11/two-sisters-text_011.png', 'one', '5701 Logan Rd', 'Kansas City', 'MO', 64136, 'vendor', 'http://www.twosisterscateringkc.com/', 'From a business lunch to your elaborate social event of the year, Two Sisters Catering’s homemade touch and elegance goes into everything we make. Our delicious recipes and eye-appealing dishes have been a Kansas City favorite for more than 10 years.'),
('eacatering@gmail.com', 'Lars', 'Hettfield', 'http://www.eacatering.com/publishImages/~master~master~~master7.jpg', 'one', '8011 Wornall Road', 'Kansas City', 'MO', 64114, 'vendor', 'http://www.eacatering.com/', 'EA Catering & Sons is chef-owned and operated in Kansas City, MO. Since opening in 2006, we’ve treated every customer like they were a part of our family. We are a full service caterer. We create a custom from scratch menu just for you. We can also take care of all your event planning needs. . Chef Argie is a graduate  of the Culinary Institute of America in Hyde Park, New York. He is well reviewed and has 30 years experience in the industry. Free event venue with minimum order! We never cut corners, we use the best natural ingredients we can find, we make everything from scratch. We never use processed or any pre-made foods you will love the difference. Eat Good Live Well!'),
('PavilionBanquet@gmail.com', 'Kacie', 'McClusky', 'https://static.wixstatic.com/media/c1b583_254177e740d340c3a7dc59d7910d4152~mv2_d_4144_1318_s_2.png/v1/fill/w_600,h_190,al_c,q_85,usm_0.66_1.00_0.01/c1b583_254177e740d340c3a7dc59d7910d4152~mv2_d_4144_1318_s_2.webp', 'one', '14831 E US Highway 40', 'Kansas City', 'MO', 64136, 'vendor', 'https://www.pavilioneventspace.com/', 'Boasting over 10,000 Square Feet Of Freshly Renovated Event Space, The Pavilion Event Space, is the Perfect Venue for your Wedding or Special Event! Showcasing Antique Bronze Ceilings, 15 Swarovski Crystal Chandeliers, Hickory Hardwood Floors, 40 foot Archways Trimmed in Stone, a 112 foot long Grand Chandelier Aisle, The Most Unique Outdoor Ceremony Space in town, and a central location near four Major Highways...What else could you ask for?'),
('theview@kchopps.com', 'Harry', 'Potter', 'http://theviewatbriarcliff.com/wp-content/uploads/2017/12/TheView_Logo-272x300.png', 'one', '4000 North Mulberry Drive', 'Kansas City', 'MO', 64116, 'vendor', 'http://theviewatbriarcliff.com/', 'Our 20-foot floor-to-ceiling windows are sure to amaze your guests upon entry, providing a panoramic view of the Kansas City skyline. While your guests are marveling at the picturesque scenery, they will be dining on innovative cuisine prepared by our Executive Chef and dancing and celebrating the night away in our stylish 7,200 square foot ballroom.'),
('info@2016mainkc.com', 'Ginny', 'Granger', 'http://static1.squarespace.com/static/57d81c80579fb38706d5d5e5/t/5c1276204fa51aee02fd70ae/1582913382380/?format=1500w', 'one', '2016 Main St', 'Kansas City', 'MO', 64108, 'vendor', 'http://www.2016mainkc.com/', '2016 Main sits at the threshold of Downtown Kansas City’s Crossroads district. Recently renovated, it offers modern amenities in a beautiful art gallery setting full of character and original architectural details now fused with contemporary aesthetics. The venue epitomizes the rich soul of its Crossroads roots, while simultaneously achieving a level of elegance and refinement not often seen in the endearingly eclectic surrounding area. With our recent addition we can accommodate groups of up to 250 while rich details throughout warm the space making it perfectly cozy for more intimate gatherings. Featuring ebony hardwood floors, marble accents, private bridal suite and more, the balance between modern luxury and vintage charm results in a stunning space in the heart of KC.'),
('hello@skylinerooftops.com', 'Johnny', 'Utah', 'https://static1.squarespace.com/static/6010d580e6d31b0d1c325cbb/t/601c50d13f2e8e76d14c38d1/1618105144005/?format=1500w', 'one', '2100 Central St', 'Kansas City', 'MO', 64108, 'vendor', 'https://www.skylinerooftops.com/', 'Are you ready to elevate your event? Skyline Rooftops offers 4 unique rooftop venues, all with stunning views of Downtown Kansas City. Whether you are hosting 10 or 200 guests, we have the perfect spot to celebrate your biggest day.'),
('info@cellar222.com', 'Steve', 'Cougar', 'https://static.wixstatic.com/media/da2a1a_63b63bf885d74145a23bc26438c7f47e~mv2.jpg/v1/fill/w_150,h_136,al_c,q_80,usm_0.66_1.00_0.01/logo.webp', 'one', '222 W 20th Street', 'Kansas City', 'MO', 64108, 'vendor', 'https://www.cellar222.com/', 'Cellar 222 is an upscale intimate Wine Cellar loaded with character in the heart of Kansas City. We are told still the best kept secret for one of a kind quaint Receptions, Corporate Events, and Parties. Our clients and couples love our fun and relaxed low stress vibe. A cozy and rustic setting with Italian forged iron lighting, natural stone fireplace, hand cut travertine floor, old world bar, plus... a really big posh comfy Bridal/VIP suite!'),
('info@AbbottEventsKC.com', 'Lucy', 'McDonald', 'https://static.wixstatic.com/media/71c685_ddb1f37a8406449e80834c79b4060d92~mv2.png/v1/crop/x_0,y_28,w_1667,h_611/fill/w_263,h_94,al_c,q_85,usm_0.66_1.00_0.01/Final%20Abbott%20Events%20Logo.webp', 'one', '1720 Cherry St', 'Kansas City', 'MO', 64108, 'vendor', 'https://www.abbotteventskc.com/cherryhall', 'Cherry Hall is located in the historic Crossroads Arts District of Kansas City. This venue holds 220 guests, and the contemporary and intricate decor is thoughtfully designed to fit the needs of any event. With a versatile indoor and outdoor space, Cherry Hall is the perfect venue to host your next event!'),
('info@ultrapom.com', 'Carolyn', 'Schwartz', 'https://ultrapom.com/wp-content/themes/ultrapom_renting/images/162x46xultrapom-logo-for-web-retina.gif,qx94285.pagespeed.ic.owBiXhWPhz.png', 'one', '3175 Terrace Street', 'Kansas City', 'MO', 65111, 'vendor', 'https://ultrapom.com/', 'Ultrapom Event Rental is your source for all your event rental needs.  We have both your basic folding tables and chairs, as well as your specialty rental needs, like gold flatware and sequin tablecloths. We are located in Kansas City, with delivery and pick up available to events in the metro and surrounding areas.'),
('info@northalndpartyrentals.com', 'James', 'Dahl', 'https://files.sysers.com/cp/upload/northlandpartyrentals/editor/NorthlandLogo-Original.png', 'one', '12600 N Woodland Ave Building D', 'Kansas City', 'MO', 64165, 'vendor', 'https://www.northlandpartyrentals.com/', 'Northland Party Rentals is located here in Kansas City, Missouri. We offer a full range of services including bounce houses, water slides, concessions, tables & chairs, and character appearances. We love doing large events and parties of any sort! Leave the delivery, set-up, and takedown to us. We do deliver all over the Kansas City metro, yes that does include the Kansas side. We also work with multiple other vendors to make sure your full party or event is a success!'),
('info@kcpartyrentals.com', 'Lisa', 'Wellington', 'https://files.sysers.com/cp/upload/jumpingmonkeyskc/editor/full/logo.png', 'one', '6620 Royal St', 'Pleasant Valley', 'MO', 64068, 'vendor', 'https://www.kcpartyrentals.com/', 'It’s all about the experience. We have years of experience providing customizable, creative and unique events to you and your party goers. Whether that is a back yard birthday party for your child or a large corporate event with tents, inflatables and more we have done it all. We provide the best customer service experience in Kansas City, from our experienced event coordinators and office staff to the happy staff that help deliver, set up and take down your events. We strive not to be just another party rental company, we strive to be the best. Lastly, our inventory allows you to provide the ultimate experience for your guests. We have one of the largest inventories in Kansas City and it is growing weekly. Need something you don’t see, often times we will go get it so we can be your one stop shop. Just Ask.'),
('info@marqueeeventrentals.com', 'Mike', 'Holmes', 'https://re-mm-assets.s3.amazonaws.com/site_setting/1/original_MarqueeLogo_1519237715.svg', 'one', '5050 Kansas Ave', 'Kansas City', 'KS', 66106, 'vendor', 'https://marqueerents.com/', 'We are proud to announce we have officially become Marquee. We have united six of the best companies into one premier event company. As a result, Marquee combines great people and products to provide you with more event expertise, and the deepest inventory in the industry. Our resources and capabilities allow us to uniquely partner with clients to execute any type or size of event across Midwest and Southern markets. One passionate team of experts 100% Committed to ensure client satisfaction every day, every event.'),
('info@carnivaltimes.com', 'Adam', 'Brody', 'https://static1.squarespace.com/static/538a68a0e4b0ba8d706a6578/t/6074da23392a054975b8d4a0/1618271317972/?format=1500w', 'one', '5200 NE 48th St', 'Kansas City', 'MO', 64119, 'vendor', 'https://www.carnivaltimes.com/', 'Carnival Times is your premiere provider of all your party rental needs. We carry over 150 unique party attractions, from moonwalks to mechanical bulls. Needing a cotton candy machine or bouncer for your next birthday party? We offer up to 6-hour rentals and can provide overnight, or multi-day rental services. Inflatables such as obstacle courses, giant slides, and even jousting arenas are available for any type of event.  Looking for something unique? We carry foam dance party pits, “Hoss” the Mechanical Hog, and 27’ Rock Walls, too! Did you know we also carry photo booths and Single Euro-Bungee’s.'),
('info.josefiestas@gmail.com', 'Jose', 'Martin', '', 'one', '4832 E 9th Street', 'Kansas City', 'MO', 64124, 'vendor', 'https://josefiestas.com/', 'Whether it is your daughters elegant  wedding reception  or your sons graduation celebration, we have got what you are looking for at Jose Fiestas. We carry tents, tables, chairs, linens, balloon decor, portable staging and much more!'),
('info@elitesounds.com', 'Sam', 'Gibson', 'https://static1.squarespace.com/static/581fbcd2ebbd1a19864a1322/t/5ed6b1639c031531300a37b7/1618455549602/?format=1500w', 'one', '1124 W 25 St', 'Kansas City', 'MO', 64108, 'vendor', 'https://www.elitesoundskc.com/#elite-sounds', 'Elite Sounds has established itself as one of the most skilled, entertaining and original event DJ companies in Kansas City. We don’t simply play music or set up lighting. We create an experience. From wedding receptions and high school dances to corporate holiday parties and fundraisers, we team with our clients to ensure each event is a reflection of their vision.  Expect experienced, award winning entertainers to facilitate every aspect of your event while leaving guests exhausted from high energy dancing!'),
('info@crystalproductionsdj.com', 'Junior', 'Babcock', 'https://crystalprokc.com/wp-content/uploads/2020/06/Logo.jpg', 'one', '2500 W Pennway St', 'Kansas City', 'MO', 64108, 'vendor', 'https://crystalprokc.com/', 'Crystal Productions DJ Services is the perfect complement to any event. We are a family owned company that specializes in DJ services for weddings, corporate events, parties, you name it! We offer a variety of other services to incorporate into your exciting day! Not only will your guests dance the night away, they can enjoy a photo booth and remember the night for days, even months to follow.'),
('djalexreedkc@gmail.com', 'Alex', 'Reed', 'http://djalexreed.com/wp-content/uploads/2017/03/DJAlexReed-Website-Logo-1.png', 'one', '1219 Union Ave', 'Kansas City', 'MO', 64101, 'vendor', 'https://djalexreed.com/', 'I was born and raised in Kansas growing up in Shawnee, where I graduated high school and went to Pittsburg State University for my undergraduate degree. Music has always been a passion of mine growing up playing different instruments and listening to a variety of genres. I began DJing in the summer of 2010 because I was tired of listening to the same music at parties, weddings and bars. I have a vast knowledge of music and an eye for the crowd, so I decided to put my skills to work.'),
('dancefactory@gmail.com', 'Devon', 'Paul', '', 'one', '', 'Kansas City', 'MO', 64108, 'vendor', 'https://www.wedj4u.com/home.html', 'Our specialty is filling dance floors and making sure you and your guests have a great time!  We moved here in 2014 and since have performed at over 200 venues in and around Kansas City; winning The Knot Bridal Magazines "Best of Weddings" award 6-years in-a-row, supported numerous area charities, and are extremely proud to have been selected as the Official DJs for The Kansas City Chiefs ​"Ultimate Tailgate Party" held inside Arrowhead Stadium!​'),
('djhydan@gmail.com', 'Hydan', '', 'http://static1.squarespace.com/static/5a01c7c5d7bdce98fb7e8b06/t/5a5bfa57652dea17cc3219c4/1574230673654/?format=original', 'one', '', 'Kansas City', 'KS', 66101, 'vendor', 'http://djhydan.com/', 'HYDAN is an open format vinyl DJ based out of Kansas City. HYDAN grew up with a background in music, teaching himself how to play the piano at a very young age. HYDAN went on to play piano professionally until he discovered his passion for DJing while studying at the University of Kansas. In Lawrence, HYDAN helped build huge followings to what has become one of the most popular bars in the city and HYDAN quickly became one of the most followed DJs in Lawrence.'),
('info@levity.com', 'Derek', 'Styles', 'https://lirp.cdn-website.com/4fb9608c/dms3rep/multi/opt/Gray_Levity_Logo_Transparent_Background-cropped-426w.png', 'one', '1633 Swift St', 'Kansas City', 'MO', 64116, 'vendor', 'https://www.kcmobiledj.com/', 'Making Celebrations Easier');


--USERS_PHOTOS:
--Fill users_photos with fake user's profile photos:
INSERT INTO "users_photos" ("userId", "photo")
VALUES (1, 'https://karaspartyideas.com/wp-content/uploads/2016/11/Bike-Themed-Birthday-Party-via-Karas-Party-Ideas-KarasPartyIdeas.com28.jpeg'), 
(2, 'https://partycity6.scene7.com/is/image/PartyCity/_pdp_sq_?$_1000x1000_$&$product=PartyCity/819485'), 
(3, 'http://basementrejects.com/wp-content/uploads/2014/08/dungeons-dragons-2000-thora-birch-riding-dragon-savina-300x166.jpg'), 
(4, 'https://www.rawmusictv.com/images/og-share-image/best-swedish-rock-bands.jpg'), 
(5, 'https://www.alpineartscenter.org/images/stories/setup_pictures/birthday%20copy.jpg'), 
(6, 'https://images.ctfassets.net/cnu0m8re1exe/4jaJ338Mbgu42tfIVnvWbp/e2c7e11773ff21b6d6f073fe8b87ece7/shutterstock_734992102.jpg?w=650&h=433&fit=fill');


--VENDORS:
--Fill vendors tables with fake users with type "vendor"
INSERT INTO "vendors"
("vendorUserId", "companyName", "description", "additionalInfo", "phone")
VALUES
(2, 'Sir Knights Rentals', 'My company provides the realest Rennaissance experience you can get.', 'I am a small, family-run business.  You will be blown away by what good jesters my kids make!', '888-777-6666'),
(4, 'Rockin Johns', 'My Liberty Rockers will liven up your party no matter how small or large.', 'We are certified to play anywhere in the Kansas City metro.', '999-000-1234'),
(6, 'The Magical Mushroomer', 'I have been rated the Most-Luscious Mushroom Grower 5 years running.', 'I am approved by the FDA.', '567-890-4567'),
(7, 'Mintahoe', 'When you choose Mintahoe Catering &  Events, you choose pease of mind.  Our event experts will help you design the perfect menu with your vision and budget. Envision the Wow', 'We prioritize local products when available and cost-efficient to our clients.', '612-253-0255'),
(8, 'Chowgirls', 'Chowgirls creates beautiful, handcrafted fare using fresh, seasonal ingredients.', 'Strong relationships with local farmers and vendors allow our chefs to craft menus reflecting the tasts of each season and our commitment to sustainability.', '612-203-0786'),
(9, 'Naf Naf Middle Eastern Grill', 'We promise to be your guide to exploring the best flavors of the Middle East each time we make our handmade dishes, like pillowy pita, crispy falafel, savory shawarma, and our scratch-made signature sauces.', 'Middle Eastern cuisine done right.', '651-347-1119'),
(10, 'CRAVE Catering & Events', 'Inspired by our passion for quality food and our love of helping guests create one of a kind memories, CRAVE Catering is a full service Minneapolis catering company dedicated to making your event unforgettable!', 'We offer Kosher meals', '952-562-5620'),
(11, 'The Deco Catering', 'Located in Minneapolis, The Deco Catering is a premier Minnesota caterer, founded by Soile Anderson in 1982. The Deco Catering offers award winning authentic European catering rich with flavor, artistic flair, and design. With over 30 years of catering experience, The Deco Catering is a Twin Cities premier wedding caterer, corporate event caterer, and is proud to be one of a select few in Minnesota to carry a Kosher Food license.', 'Kosher Food license', '612-623-4477'),
(12, 'Common Roots Catering', 'We are a full-service Minneapolis / St. Paul caterer providing our clients with good food made from scratch and exceptional service.  We will make your event memorable with our modern take on classic American cuisine using local and organic ingredients. ', 'Local and sustainable food. Operating in an environmentaly responsible way. Values driven business.', '612-871-2360'),
(13, 'Walker On Site', 'The Walker Art Center, one of the most celebrated art museums in the country, is known for its innovative presentations and acclaimed collections across the spectrum of the visual, performing, and media arts, housed within an award-winning civic landmark. Amid beautiful galleries, the Walker also offers unique spaces for indoor and outdoor private rentals for artful celebrations, refined receptions, unforgettable weddings, and state-of-the-art corporate events. The iconic building features flexible spaces with high-tech amenities for nearly any size gathering—including a theater, street-level and roof-top terraces, plazas, gardens, and lounges.', 'Hosting your event at the Walker also provides features you won’t find anywhere else: free gallery admission, a private exhibition tour for your guests, a mini-golf outing for an afternoon away from the office, or a cocktail reception with a private screening of the British Arrow Awards to spice up your annual holiday party.', '612-253-3408'),
(14, 'FIVE Event Center', 'You spent valuable time finding the love of your life, so don’t compromise when it comes to celebrating your wedding day! FIVE Event Center is the elegant and romantic space you and your partner had always dreamed. Your personal Event Manager will walk you through every step of the way and can help tailor our space and services to fit your taste, needs,  and budget. When the date arrives, your Event Manager will be working around the clock to make sure that your celebration runs smoothly, helping create memories to last you a lifetime.', 'Our convenient Uptown location allows plenty of ease for travelers and guests being near ample on-site parking, bars, eateries, and hotels, as well as making our location suitable for special photo opportunities near infamous Minneapolis landmarks like Lake Calhoun, and the Uptown Theatre. From small affairs to large parties, FIVE Event Center can accommodate festivities that can span the entire building, offering a cozy outdoor patio perfect for breaks from the dance floor, toasts to the happy couple in our lower level cocktail room, or elevator rides back to the second floor for memorable dinner conversations.', '612-827-5555'),
(15, 'ARIA', 'As a former theater our open and flexible floor plan, soaring 30-foot ceilings, amazing acoustics, and plentiful rigging points for décor and lighting, ensure that logistics are never in the way of bringing your event dreams to life.', 'Apart from food & beverage, you are welcome to choose any vendor, though we do have our favorites!', '612-342-2742'),
(16, 'Lumber Exchange Event Center', 'The story of the Lumber Exchange Event Center all started with a simple idea. Host larger more elegant events and do it in a way that would change the way Minneapolis looked at event space.', 'We are Downtown Minneapolis’ most versatile venue, located at the intersection of Hennepin Avenue and South 5th Street in the dazzling Lumber Exchange Building.', '612-843-2575'),
(17, 'A`BULAE', 'A`BULAE is Minnesota`s first fully integrated reception venue that brings together people, events, and state-of-the-art technology. In a beautiful loft-style space overlooking downtown St. Paul, our integrated light, sound, and digital capabilities will offer you endless opportunities to personalize the space.', 'Full-service catering kitchen on-site.', '651-788-9818'),
(18, 'Midpointe Event Center', 'We`ve designed Midpointe Event Center with diverse and dynamic events in mind. Not only do we include many amenities and services in the price of your event hall rental, but our space can be customized to make your event a one-of-a-kind experience.', 'Ability to use any outside licensed caterer of your choice.  Ability to host your own bar.', '651-641-7544'),
(19, 'AmyZaroff Events + Design', 'We are a boutique, multi-channel, creative agency that has produced over 1,500 events across the United States and Canada. We are smart, fun loving and creative people brought together by a shared passion for attention to detail and bringing joy to those who attend our activations and events.', '', '333-867-5309'),
(20, 'Y&I Events', 'descDeocration & Design for Special Events of all types: Weddings, Receptions, Corporate Functions, Fundraisers, Galas, Banquets, Quinceaneras, Bar/Bat Mitzvahs, Reunions, Birthdays, and much more!ription', 'addiY&I Events starts and ends the day with our company’s core values and mission in mind: Excellence In Service, Expertise & Knowledge, Inclusiveness & Diversity, and Ethics & Integrity.', '612-618-1406'),
(21, 'The Blaisdell', 'This gorgeous, fully-restored 1915 mansion is the perfect venue for your large wedding reception, small, intimate wedding ceremony, corporate event, gala fundraiser, or private party in Minneapolis. From the grand ballroom to the spacious suite and comfortable lounge, The Blaisdell is a one-of-a-kind jewel nestled in the heart of the city. All that’s missing is you!', 'With a range of indoor and outdoor spaces, The Blaisdell allows you to create a wedding or event that reflects your personal tastes. The spacious Ballroom can accommodate up to 250 guests for dinner service while The Courtyard and The Parlor offer a beautiful space for ceremonies and cocktail hours.', '952-288-9966'),
(22, 'Blush Custom Event Decor', 'Simply put, I absolutely love all things design! Each project is an exciting challenge for me as I translate ideas and visions into real life. The special events we celebrate are often important milestones in our lives and deserve to be remembered in a beautiful way… and unique, artful statement decor will do just that for you and your guests! A stunning photo backdrop, welcome wall, or perhaps a lovely balloon piece will set the tone for these momentous occasions.', '', '651-402-5474'),
(23, 'Amazing Balloon Entertainment & Decorations', 'We specialize in quality event Balloon Entertainment, Decorations & Delivery Service for family parties, corporate functions, and workshops for all levels. With over 20 years experience, our head-turning work is perfect for all occasions, customizable to any theme or color scheme, and is guaranteed to put smiles on the faces of all your guests from ages 1-1000!', '', '612-695-1697'),
(24, 'Charmed! Boutique Decor & Floral', 'Distinctive decor, floral & styling for weddings & events in Minneapolis, St. Paul & the Twin Cities Metro Area of Minnesota.', 'Styles ranging from Rustic & Elegant to Tuscan Stone, Gold & Crystal, and many more.', '612-382-2960'),
(25, 'A & J Party and Event Rental', 'We bring all of your rental needs to you! No matter your location whether it be Minneapolis, Edina, Lakeville, Bloomington, Farmington Apple Valley or any surrounding Twin Cities area, we charge a reasonable fee to ensure you have what you need for your event. Tables, Chairs, Canopies, and much more- We have what you need to make your party the best it can be!', '', '612-708-3421'),
(26, 'Broadway Party & Tent Rental', 'Broadway is a Local Family Owned business & since 1956 we’ve dedicated ourselves to providing quality rental equipment to our community! We’re 2nd Generation owned & operated! Learn more about buying local.', 'Booking your rental products long before the date of your event reduces rushed decisions and gives sufficient time for you and Broadway Party & Tent Rental to work together to plan and prepare an enjoyable event. Ordering early also increases the probability that the products, delivery, and pickup times you want will be available. Last minute changes can be counterproductive and may have adverse affects on an otherwise successful event. At Broadway Party & Tent Rental we make every effort to help you make the best choices for your event!', '763-208-1357'),
(27, 'Minnesota Ice', 'MINNESOTA ICE IS THE LEADING PRODUCER OF PACKAGED ICE, PURE & CLEAR COCKTAIL ICE, KOLD DRAFT ICE CUBES, CRUSHED ICE, SHAVED ICE BLOCKS, SCULPTURE ICE BLOCKS, AND ICE SCULPTURES', '', '612-254-8330'),
(28, 'Occasions Linen Rental', 'Whether it’s an intimate gathering or larger gala your event will be remembered for a lifetime. Specialty linens are key to a spectacular table setting and to creating your desired atmosphere. Just remember that your event will be photographed over and over…so you really want to make a lasting impression! Occasions Linen Rental services the Twin Cities and surrounding communities. If there is something that you don’t see on the website let us know we can order it! Together we can create your occasion to remember.', '', '651-387-1726'),
(29, 'Festivities', 'Festivities has the functional, fun & fashionable stuff your event needs, with the design, service & expertise you want.', 'We specialize in weddings, social events, and coproate / non-profits.', '763-682-4846'),
(30, 'Apres Event Decor & Tent Rental', 'I started Après 33 years ago out of the lower level of my home. Purchasing a full line of rental inventory and opening at my first location in time for the hectic Christmas season of 1987. We are now working out of more than 63,000 square feet.', 'Serving Minneapolis, St. Paul, Twin Cities, Minnesota, Wisconsin, Iowa, North Dakota, South Dakota', '952-942-3399'),
(31, 'A Touch of Magic Entertainment', 'We are a family owned and operated full-service entertainment company run by professional entertainers.  Founded in 1986, A Touch of Magic, Inc. is located in St. Paul, Minnesota, the Twin Cities, with entertainers/artists who are nationally renowned in addition to being local favorites. What started as a small project to fund a college education,  has grown into a lifelong passion and desire to bring joy & laughter to our clients!  Maybe that’s why we’ve been named “Best Entertainment” in the Twin Cities over and over again.', 'A Touch of Magic, a Certified Women’s Business Enterprise, specializes in top notch, age-appropriate entertainment for ages 3-93, reasonable prices, and unsurpassed customer support. Through our commitment, experience, and expertise, we have established a business relationship with our customers that is lasting a lifetime.', '651-748-9442'),
(32, 'Karaoke Twin Cities', 'We provide hosted karaoke entertainment to local bars/restaurants as well as the opportunity to rent our equipment with or without a host to suit your entertainment needs.', 'We  deliver karaoke anywhere in the Twin Cities greater metro area. We may  be willing to travel farther for an additional fee, see our delivery map page for more info.', '612-889-7963'),
(33, 'Northern Sound', 'The owners of Northern Sound Entertainment have a serious passion for the event service industry. They started this company in 2016 with a vision to shake up the Wedding and Event Services industry.', 'Event DJ, Photo Booth, Event Videos, Karaoke', '612-306-2831'),
(34, 'WedPhoria', 'Your 1-Stop-Shop for Wedding & Special Event Services!', 'DJ, Photography, Videography, Event Planning, Photo Booths', '612-293-764'),
(35, 'Adagio Djay Entertainment', 'When the lights go up and the party’s over, all you’ll have left are the memories. At Adagio Djay Entertainment, we specialize in crafting a symphony of music, melodies and excitement into the perfect experience for the most memorable day of your life. From the first dance to the last—we never forget whose day it is.', '', '612-787-3501'),
(36, 'Midwest Sound DJ Entertainment', 'We created the blueprint for wedding DJ entertainment. We continue to set trends and facilitate remarkable receptions. Our unparalleled training and mentorship program makes our DJs exceptional. We perform at 1,900 receptions every year and each is customized to be one of a kind. Our comprehensive online planning process lets our clients have complete control to guarantee a unique and memorable wedding. With our experience and reliability, we will continue to provide amazing wedding DJ entertainment for many years to come.', '', '651-644-4111'),
(37, 'Brancato`s Catering', 'Whether you’re planning an outdoor event or working with one of Kansas City’s hottest venues, our expert coordinators will offer you the latest in food trends and make your event one to remember. We work closely with Kansas City’s top event venues to help provide you with the best service possible for your big day. If you haven’t selected your venue yet we can help guide you in finding the perfect fit for your big day. Our coordinators will work with you from planning to execution, providing you with expert guidance leading up to your event and throughout your big day making sure your expectations are exceeded.', 'Food is important to the success of your event and our reception – wedding catering is designed to accommodate various budgets. Our customizable options are designed to fit the needs of your event. Brancato’s Catering, selected as one of the city’s best caterers, offers everything from full-service seated dinners, buffets and appetizers to quick and easy drop-off orders. We also offer full liquor packages, bartenders, room flip service, closing service and cake cutting.', '815-765-4707'),
(38, 'Moxie Catering & Event Design', '', '', '816-561-0384'),
(39, 'Blue Pot Catering', 'Kansas City’s premier catering and event designer for weddings, corporate and social events, since 2006. Delight your guests with seasonal, made-from-scratch menu items inspired by the best ingredients.', 'Custom Menus', '816-916-0169'),
(40, 'Grandma`s Catering', '', '', '816-472-6362'),
(41, 'Two Sisters Catering', 'From a business lunch to your elaborate social event of the year, Two Sisters Catering’s homemade touch and elegance goes into everything we make. Our delicious recipes and eye-appealing dishes have been a Kansas City favorite for more than 10 years.', 'additionalInfo', '816-737-0846'),
(42, 'EA Catering & Event Space', 'EA Catering & Sons is chef-owned and operated in Kansas City, MO. Since opening in 2006, we’ve treated every customer like they were a part of our family. We are a full service caterer. We create a custom from scratch menu just for you. We can also take care of all your event planning needs. . Chef Argie is a graduate  of the Culinary Institute of America in Hyde Park, New York. He is well reviewed and has 30 years experience in the industry. Free event venue with minimum order! We never cut corners, we use the best natural ingredients we can find, we make everything from scratch. We never use processed or any pre-made foods you will love the difference. Eat Good Live Well!', 'At EA Catering we specialize in fresh, from scratch, healthy food. We use organic produce. Free range, hormone and antibiotic free poultry and free range, grass fed beef. We bake our own bread. Roast and smoke our meats in house. No GMO`s! No HFCS! Just good clean food. We know you will taste and feel the difference. Eat Good Live Well', '913-961-6226'),
(43, 'The Pavilion Event Space', 'Boasting over 10,000 Square Feet Of Freshly Renovated Event Space, The Pavilion Event Space, is the Perfect Venue for your Wedding or Special Event! Showcasing Antique Bronze Ceilings, 15 Swarovski Crystal Chandeliers, Hickory Hardwood Floors, 40 foot Archways Trimmed in Stone, a 112 foot long Grand Chandelier Aisle, The Most Unique Outdoor Ceremony Space in town, and a central location near four Major Highways...What else could you ask for?', 'Stock your own Bar. Open Vedor / Catering Policy. Space to Comfortably Seat 300', '816-478-4848'),
(44, 'The View at Briarcliff', 'Our 20-foot floor-to-ceiling windows are sure to amaze your guests upon entry, providing a panoramic view of the Kansas City skyline. While your guests are marveling at the picturesque scenery, they will be dining on innovative cuisine prepared by our Executive Chef and dancing and celebrating the night away in our stylish 7,200 square foot ballroom. Our professional and experienced planners will help guide you through any type of event including weddings, receptions, corporate gatherings, private parties, formal dinners and more. Whether you’re hosting for 5 or 500, our elegant ballroom can be divided to suit your party needs. From a fully customizable menu to décor, to seamless service, The View at Briarcliff is sure to offer a memorable experience for all.', 'LEED certified venue. Located inside the luxurious Courtyard marriott', '816-841-2361'),
(45, '2016 Main', '2016 Main sits at the threshold of Downtown Kansas City’s Crossroads district. Recently renovated, it offers modern amenities in a beautiful art gallery setting full of character and original architectural details now fused with contemporary aesthetics. The venue epitomizes the rich soul of its Crossroads roots, while simultaneously achieving a level of elegance and refinement not often seen in the endearingly eclectic surrounding area. With our recent addition we can accommodate groups of up to 250 while rich details throughout warm the space making it perfectly cozy for more intimate gatherings. Featuring ebony hardwood floors, marble accents, private bridal suite and more, the balance between modern luxury and vintage charm results in a stunning space in the heart of KC.', 'Additional services available', '816-674-6900'),
(46, 'Skyline Rooftops', 'Are you ready to elevate your event? Skyline Rooftops offers 4 unique rooftop venues, all with stunning views of Downtown Kansas City. Whether you are hosting 10 or 200 guests, we have the perfect spot to celebrate your biggest day.', '14 hour rental. Free parking. Vendor flexibility.', '913-777-4488'),
(47, 'Cellar 222', 'Cellar 222 is an upscale intimate Wine Cellar loaded with character in the heart of Kansas City. We`re told still the best kept secret for one of a kind quaint Receptions, Corporate Events, and Parties. Our clients and couples love our fun and relaxed low stress vibe. A cozy and rustic setting with Italian forged iron lighting, natural stone fireplace, hand cut travertine floor, old world bar, plus... a really big posh comfy Bridal/VIP suite!', '', '913-522-4770'),
(48, 'Abbott Events', 'Cherry Hall is located in the historic Crossroads Arts District of Kansas City. This venue holds 220 guests, and the contemporary and intricate decor is thoughtfully designed to fit the needs of any event. With a versatile indoor and outdoor space, Cherry Hall is the perfect venue to host your next event!', '', '816-982-1014'),
(49, 'Ultrapom', 'Ultrapom Event Rental is your source for all your event rental needs.  We have both your basic folding tables and chairs, as well as your specialty rental needs, like gold flatware and sequin tablecloths. We are located in Kansas City, with delivery and pick up available to events in the metro and surrounding areas.', '', '816-525-8568'),
(50, 'Northland Party Rentals', 'Northland Party Rentals is located here in Kansas City, Missouri. We offer a full range of services including bounce houses, water slides, concessions, tables & chairs, and character appearances. We love doing large events and parties of any sort! Leave the delivery, set-up, and takedown to us. We do deliver all over the Kansas City metro, yes that does include the Kansas side. We also work with multiple other vendors to make sure your full party or event is a success!', 'Our staff is professionally trained on all safety and cleanliness procedures. Our service and dedication to our clients are unsurpassed. Our goal is to offer the largest, quality selection of supplies, products, and customer service to supply our customers` needs. We continuously order and receive new products to ensure we always have the best products for you, our customers. We will continue going out of our way to make sure the needs of our amazing customers are met.1', '816-785-3917'),
(51, 'KC Party Rentals', 'It`s all about the experience. We have years of experience providing customizable, creative and unique events to you and your party goers. Whether that`s a back yard birthday party for your child or a large corporate event with tents, inflatables and more we`ve done it all. We provide the best customer service experience in Kansas City, from our experienced event coordinators and office staff to the happy staff that help deliver, set up and take down your events. We strive not to be just another party rental company, we strive to be the best. Lastly, our inventory allows you to provide the ultimate experience for your guests. We have one of the largest inventories in Kansas City and it is growing weekly. Need something you don’t see, often times we will go get it so we can be your one stop shop. Just Ask.', '', '816-945-9181'),
(52, 'Marquee Event Rentals', 'We are proud to announce we have officially become Marquee. We have united six of the best companies into one premier event company. As a result, Marquee combines great people and products to provide you with more event expertise, and the deepest inventory in the industry. Our resources and capabilities allow us to uniquely partner with clients to execute any type or size of event across Midwest and Southern markets. One passionate team of experts 100% Committed to ensure client satisfaction every day, every event.', 'We have your event needs covered, from beverage services to staging. Get in touch today to learn more about our products and services or to request a complimentary consultation with an event specialist.', '816-765-1444'),
(53, 'Carnival Times', 'Carnival Times is your premiere provider of all your party rental needs. We carry over 150 unique party attractions, from moonwalks to mechanical bulls. Needing a cotton candy machine or bouncer for your next birthday party? We offer up to 6-hour rentals and can provide overnight, or multi-day rental services. Inflatables such as obstacle courses, giant slides, and even jousting arena`s are available for any type of event.  Looking for something unique? We carry foam dance party pits, “Hoss” the Mechanical Hog, and 27’ Rock Walls, too! Did you know we also carry photo booths and Single Euro-Bungee’s.', 'Carnival Times serves the entire KC Metro Area, including Platte City, Kearney, Lee`s Summit, Blue Springs, Overland Park, Kansas City, Independence, and more.', '816-569-2855'),
(54, 'Jose Fiestas Rental', 'Whether it`s your daughter`s elegant  wedding reception  or your son`s graduation celebration, we`ve got what you`re looking for at Jose Fiestas. We carry tents, tables, chairs, linens, balloon decor, portable staging and much more!', 'We`re small enough to offer personalized service yet large enough to deliver exactly what you need.', '816-231-5764'),
(55, 'Elite Sounds', 'Elite Sounds has established itself as one of the most skilled, entertaining and original event DJ companies in Kansas City. We don’t simply play music or set up lighting. We create an experience. From wedding receptions and high school dances to corporate holiday parties and fundraisers, we team with our clients to ensure each event is a reflection of their vision.  Expect experienced, award winning entertainers to facilitate every aspect of your event while leaving guests exhausted from high energy dancing!', 'KMBC’s A-List Competition Awards: Best DJ Company, 2009; Wedding Wire’s Couples Choice Awards, 2010 - 2020; The Knot Best Of Weddings Awards: 2011, 2013 - 2020; The Knot Best of Weddings Hall of Fame; and Best of Borrowed & Blue Weddings, 2016 - 2017.', '816-559-8080'),
(56, 'Crystal Productions DJ Service', 'Crystal Productions DJ Services is the perfect complement to any event. We are a family owned company that specializes in DJ services for weddings, corporate events, parties, you name it! We offer a variety of other services to incorporate into your exciting day! Not only will your guests dance the night away, they can enjoy a photo booth and remember the night for days, even months to follow.', 'We want to play a vital role in your celebration whether it be a wedding, corporate event, or party, we want to support you! It takes a team of professionals to pull off the most memorable event and we would love to be your local event DJ, uplighting professional, and photo booth connoisseur. When picking your DJ entertainment, you want to be sure they are the perfect fit for you and your guests for your special celebration. Please be sure to contact us to discuss the best options for your event!', '816-979-3657'),
(57, 'DJ Alex Reed', 'I was born and raised in Kansas growing up in Shawnee, where I graduated high school and went to Pittsburg State University for my undergraduate degree. Music has always been a passion of mine growing up playing different instruments and listening to a variety of genres. I began DJing in the summer of 2010 because I was tired of listening to the same music at parties, weddings and bars. I have a vast knowledge of music and an eye for the crowd, so I decided to put my skills to work.', '', '913-744-9641'),
(58, 'The Dance Factory', 'Our specialty is filling dance floors and making sure you and your guests have a great time!  We moved here in 2014 and since have performed at over 200 venues in and around Kansas City; winning The Knot Bridal Magazine`s "Best of Weddings" award 6-years in-a-row, supported numerous area charities, and are extremely proud to have been selected as the Official DJ`s for The Kansas City Chief`s ​"Ultimate Tailgate Party" held inside Arrowhead Stadium!​', '', '816-260-7379'),
(59, 'DJ Hydan', 'HYDAN is an open format vinyl DJ based out of Kansas City. HYDAN grew up with a background in music, teaching himself how to play the piano at a very young age. HYDAN went on to play piano professionally until he discovered his passion for DJing while studying at the University of Kansas. In Lawrence, HYDAN helped build huge followings to what has become one of the most popular bars in the city and HYDAN quickly became one of the most followed DJs in Lawrence.', '', '913-708-5277'),
(60, 'Levity Weddings & Events', 'Making Celebrations Easier', 'Owning a business is more than providing an amazing product or stellar service.  It`s important to be able to use the privilege of our success and give back to make a positive impact in our community.  Levity takes pride in donating services each year to benefit worthy causes.  From birthday parties for under-privileged youth, fundraisers that help homeless families get off the streets for good or assisting organizations trying to give every child a warm and loving home.  On top of that, all of our past and present heroes of the armed forces receive a 10% upgrade credit.', '816-974-3005');


--Fill vendors_features table with real special_features data for the fake vendors:
INSERT INTO "vendors_features"
("vendorUserId", "featureId")
VALUES 
(2, 3), (4, 3), (6, 1), (6, 3), (4, 3), (7, 3), (8,1), (9, 2), (11, 2), (12, 1),
(14, 3), (15, 1), (16, 3), (17, 2), (18, 1), (19, 1), (21, 1), (22, 1), (23, 3),
(24, 2), (25, 3), (26, 2), (27, 2), (28, 1), (29, 2), (30, 3), (31, 1), (32, 2),
(35, 3), (36, 3), (37, 1), (39, 2), (41, 1), (43, 1), (44, 2), (45, 3), (47, 3),
(49, 1), (51, 3), (52, 2), (55, 3), (57, 3), (59, 3);

--Fill vendors_services table with real service_types data for the fake vendors:
INSERT INTO "vendors_services"
("vendorUserId", "serviceId")
VALUES
(2, 5), (2, 2), (4, 5), (4, 2), (6, 1), (6, 3), (7, 1), (8, 1), (9, 1), (10, 1),
(11, 1), (12, 1), (13, 2), (14, 2), (15, 2), (16, 2), (17, 2), (18, 2), (19, 3),
(20, 3), (21, 3), (22, 3), (23, 3), (24, 3), (25, 4), (26, 4), (27, 4), (28, 4),
(29, 4), (30, 4), (31, 5), (32, 5), (33, 5), (34, 5), (35, 5), (36, 5), (37, 1),
(38, 1), (39, 1), (40, 1), (41, 1), (42, 1), (43, 2), (44, 2), (45, 2), (46, 2),
(47, 2), (48, 2), (49, 4), (50, 4), (51, 4), (52, 4), (53, 4), (54, 4), (55, 5),
(56, 5), (57, 5), (58, 5), (59, 5), (60, 5);


--MESSAGES
--Insert fake messages to start conversations:
INSERT INTO "messages" ("fromUser", "toUser", "message")
VALUES (1, 2, 'What is your rate for 100 people?'), 
(1, 4, 'Is your band able to play in Smithville?'), 
(3, 4, 'Are you available to play a wedding in August?'),
(5, 6, 'Are you licensed to serve your mushrooms in downtown Minneapolis?');

--Insert fake responses to fake messages separately so that the timestamp is different:
INSERT INTO "messages" ("fromUser", "toUser", "message")
VALUES (2, 1, 'I would like to discuss what activities you would like included- are you available to speak over the phone?'), 
(4, 3, 'What day in August?');


--EVENTS:
--Create fake events for the fake Planners
INSERT INTO "events" ("plannerUserId", "dateOfEvent", "timeOfEvent", "address", 
"city", "state", "zip", "numberOfAttendees", "description")
VALUES (1, '2021-04-30', '3:00', '5600 Walnut', 'Smithville', 'MO', 64089, 50, 'Graduation celebration!'),
(3, '2021-08-17', '12:00', '75 Chestnut', 'Lawrence', 'KS', 64048, 200, 'Small wedding with our closest friends and family.'),
(5, '2021-05-05', '5:55', '5 Main St.', 'Minneapolis', 'MN', 55111, 1000, 'Huge Cinco de Mayo art fair.');

--Pair fake events with types_of_events
INSERT INTO "events_types" ("eventId", "typeId")
VALUES (1, 5), (2, 1), (3, 7);

--Pair fake vendors with fake events
INSERT INTO "events_vendors" ("vendorUserId", "eventId")
VALUES (2, 1), (4, 2), (6,3);